name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "triage-needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the sections below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature and its Use Cases
      description: Describe the feature you want and how it would be used
      placeholder: |
        Describe the feature and its potential use cases:
        - What is the feature?
        - How would users benefit from it?
        - What scenarios would this feature address?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references
      placeholder: Screenshots, links, examples, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct and join our Discord
      options:
        - label: I have joined the [Discord server](https://discord.gg/hjUhu33uAn) and will post updates there
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true
